### ISSUE TITLE
Raw Data is not formatted as correct JSON

### ISSUE THREAD

**Issue by jordiorlando** [JordiOrlando/keyboard-layout-editor#5]
JSON should be properly escaped.

**Comment by jordiorlando** [comment]
@iandoug Is your fork public? I'd love to take a look at what you're doing.

**Comment by iandoug** [comment]
Re the Json, Ian Prest deliberately made a 'lite' parser to avoid using all the "s, but I think it came back to bite him.
As mentioned previously, I am a total newbie with using Git, so I have just downloaded the repos and played around locally. I can send you my changed files. I see ijprest is also using the "n" character in his markup which breaks my little conversion program. The correct fix will be to generate proper Json in the first place instead of trying to fix it afterwards. Does github allow private messages? Can't see where.

**Comment by jordiorlando** [comment]
I'm trying to completely get rid of his jsonl thing and replace it with the standard JavaScript JSON parser.

As for git, you're gonna want to go to the original keyboard-layout-editor repo and then click on the "fork" button. Github will create a fork for you that you can then [clone](https://help.github.com/articles/fork-a-repo/) to your desktop. Once that's all done, just copy over the changes you've already made and then you can [commit](http://readwrite.com/2013/10/02/github-for-beginners-part-2) and [push](https://help.github.com/articles/pushing-to-a-remote/).

I don't think GitHub has private messages, but my email is jordi.orlando AT(@) gmail DOT com, feel free to email me.

**Comment by jordiorlando** [comment]
I created a Gitter so we can chat, check the readme for the link.

**Comment by jordiorlando** [comment]
Fixed as of 2bec8ff
